sudo: false

language: php

php:
  - 7.1

addons:
  postgresql: "9.5"

services:
  - postgresql

install:
  - composer self-update && composer --version
  - if [ -n "$CI_USER_TOKEN" ]; then composer config github-oauth.github.com ${CI_USER_TOKEN}; echo "Configured Github token"; fi;
  - composer global require "fxp/composer-asset-plugin:~1.1.1"

  - composer_parameters="-n --prefer-dist" # this variable will be used in all composer install commands
  - '[[ "$dependencies" != "lowest" ]] || composer_parameters="$composer_parameters --prefer-lowest"'
  - composer update $composer_parameters
  - composer_parameters="$composer_parameters --no-dev" # Codeception needs dev dependencies, but frameworks don't

before_script:
  - psql -c 'tcc;' -U postgres

script:
  - php codecept run unit