sudo: false

language: php

php:
  - 7.1

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -U postgres < src/database/CREATE_DATABASE.sql
  - psql -U postgres -d "tcc-uniararas" < src/database/CREATE_DATABASE.sql
  - psql -U postgres -d "tcc-uniararas" < src/database/CREATE_TABLE.sql
  - psql -U postgres -d "tcc-uniararas" < src/database/INSERT_VALUES.sql

script:
  - php codecept run unit --coverage --coverage-xml

after_script:
  - php vendor/bin/coveralls -v
